import { Jogo } from "./PrimeiraRodada";

export const oitavasDeFinal: Jogo[] = [
  {
    data: new Date('2022-12-03 12:00:00'),
    estadio: 'Internacional Khalifa',
    grupo: undefined,
    timeCasa: undefined,
    timeFora:  undefined,
    resultadoCasa: undefined,
    resultadoFora: undefined,
  },
  {
    data: new Date('2022-12-03 16:00:00'),
    estadio: 'Ahmad Bin Ali',
    grupo: undefined,
    timeCasa: undefined,
    timeFora:  undefined,
    resultadoCasa: undefined,
    resultadoFora: undefined,
  },
  {
    data: new Date('2022-12-05 12:00:00'),
    estadio: 'Al Janoub',
    grupo: undefined,
    timeCasa: undefined,
    timeFora:  undefined,
    resultadoCasa: undefined,
    resultadoFora: undefined,
  },
  {
    data: new Date('2022-12-05 16:00:00'),
    estadio: 'Estádio 974',
    grupo: undefined,
    timeCasa: undefined,
    timeFora:  undefined,
    resultadoCasa: undefined,
    resultadoFora: undefined,
  },
  {
    data: new Date('2022-12-04 16:00:00'),
    estadio: 'Al Bayt',
    grupo: undefined,
    timeCasa: undefined,
    timeFora:  undefined,
    resultadoCasa: undefined,
    resultadoFora: undefined,
  },
  {
    data: new Date('2022-12-04 12:00:00'),
    estadio: 'Al Thumama',
    grupo: undefined,
    timeCasa: undefined,
    timeFora:  undefined,
    resultadoCasa: undefined,
    resultadoFora: undefined,
  },
  {
    data: new Date('2022-12-06 12:00:00'),
    estadio: 'Cidade da Educação',
    grupo: undefined,
    timeCasa: undefined,
    timeFora:  undefined,
    resultadoCasa: undefined,
    resultadoFora: undefined,
  },
  {
    data: new Date('2022-12-06 16:00:00'),
    estadio: 'Lusail',
    grupo: undefined,
    timeCasa: undefined,
    timeFora:  undefined,
    resultadoCasa: undefined,
    resultadoFora: undefined,
  },
]